platform :ios, '7.1'
pod 'Reachability', '~> 3.1.1'
pod 'SDWebImage', '~> 3.6'
pod 'jastor', '~> 0.2.1'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'FPPopover', '~> 1.4.1'
pod 'WYPopoverController', '~> 0.2.2'
pod 'MBProgressHUD', '~> 0.8'
pod 'Toast', '~> 2.2'
pod 'LTUpdate', '~> 0.0.2'